using Blazored.LocalStorage;

namespace NetVigil.Client.Services
{
    public class LanguageService
    {
        private const string Key = "netvigil.lang";
        private readonly ILocalStorageService _storage;

        public string Current { get; private set; } = "en";
        public IReadOnlyList<(string Code, string Name)> Available { get; } = new[]
        {
            ("en", "English"),
            ("ru", "Русский")
        };

        public event Action? Changed;

        public LanguageService(ILocalStorageService storage)
        {
            _storage = storage;
        }

        public async Task InitAsync()
        {
            try
            {
                var stored = await _storage.GetItemAsStringAsync(Key);
                if (!string.IsNullOrEmpty(stored))
                {
                    Current = stored.Trim('"');
                }
            }
            catch { }
        }

        public async Task SetAsync(string code)
        {
            if (!Available.Any(a => a.Code == code)) return;
            Current = code;
            try { await _storage.SetItemAsStringAsync(Key, code); } catch { }
            Changed?.Invoke();
        }

        public string T(string key)
        {
            if (Strings.TryGetValue(Current, out var dict) && dict.TryGetValue(key, out var v)) return v;
            if (Strings.TryGetValue("en", out var en) && en.TryGetValue(key, out var ev)) return ev;
            return key;
        }

        public string Severity(NetVigil.Shared.RiskLevel r) => r switch
        {
            NetVigil.Shared.RiskLevel.Critical   => T("severity.critical"),
            NetVigil.Shared.RiskLevel.Anomalous  => T("severity.anomalous"),
            NetVigil.Shared.RiskLevel.Suspicious => T("severity.suspicious"),
            _                                    => T("severity.normal")
        };

        public string Role(NetVigil.Shared.UserRole r) => r switch
        {
            NetVigil.Shared.UserRole.Admin => T("admin.role.admin"),
            _                              => T("admin.role.viewer")
        };

        public string RoleFromClaim(bool isAdmin) =>
            isAdmin ? T("admin.role.admin") : T("admin.role.viewer");

        private static readonly Dictionary<string, Dictionary<string, string>> Strings = new()
        {
            ["en"] = new()
            {
                ["nav.dashboard"] = "Dashboard",
                ["nav.settings"] = "Settings",
                ["nav.profile"] = "Profile",
                ["nav.logout"] = "Logout",
                ["dashboard.title"] = "Network Dashboard",
                ["dashboard.subtitle"] = "Live monitoring active",
                ["dashboard.refresh"] = "Refresh",
                ["dashboard.scanning"] = "Scanning...",
                ["dashboard.connecting"] = "Connecting to Server...",
                ["stats.online_devices"] = "Online Devices",
                ["stats.total_traffic"] = "Total Traffic",
                ["stats.anomalies_24h"] = "Anomalies (24h)",
                ["stats.critical_devices"] = "Critical Devices",
                ["stats.devices"]  = "Online Devices",
                ["stats.traffic"]  = "Total Traffic",
                ["stats.anomalies"]= "Anomalies (24h)",
                ["stats.critical"] = "Critical Devices",
                ["chart.title"]    = "Network Traffic",
                ["chart.range"]    = "Live · last 5 min",
                ["chart.waiting"]  = "Waiting for agent data…",
                ["devices.title"]  = "Connected Endpoints",
                ["devices.empty"]  = "No devices detected. Check the agent is running.",
                ["devices.col.status"] = "Status",
                ["devices.col.name"]   = "Device",
                ["devices.col.ip"]     = "IP Address",
                ["devices.col.vendor"] = "Vendor",
                ["devices.col.seen"]   = "Last Seen",
                ["devices.online"]  = "Online",
                ["devices.offline"] = "Offline",
                ["anomalies.title"] = "Recent Anomalies",
                ["anomalies.empty"] = "No anomalies detected.",
                ["anomalies.col.time"]     = "Time",
                ["anomalies.col.device"]   = "Device",
                ["anomalies.col.severity"] = "Severity",
                ["login.title"] = "Sign in to NetVigil",
                ["login.username"] = "Username",
                ["login.password"] = "Password",
                ["login.submit"] = "Sign in",
                ["login.error"] = "Invalid credentials.",
                ["settings.title"] = "System Settings",
                ["settings.telegram"] = "Telegram Notifications",
                ["settings.telegram.enabled"] = "Enable Telegram alerts",
                ["settings.telegram.token"] = "Bot token",
                ["settings.telegram.chat"] = "Chat ID",
                ["settings.telegram.test"] = "Send test message",
                ["settings.telegram.test.ok"] = "Sent — check your Telegram.",
                ["settings.telegram.test.fail"] = "Send failed — see error.",
                ["settings.telegram.help.toggle"] = "How to set up",
                ["settings.telegram.help.title"] = "Bring your own bot — NetVigil doesn't ship one.",
                ["settings.telegram.help.step1"] = "Open <code>@BotFather</code> in Telegram, send <code>/newbot</code>, follow the prompts and copy the token it returns (looks like <code>123456789:ABC...</code>).",
                ["settings.telegram.help.step2"] = "Paste the token into the <em>Bot token</em> field above and hit Save.",
                ["settings.telegram.help.step3"] = "In Telegram, send any message to your new bot — it has to talk to you first before NetVigil can DM you.",
                ["settings.telegram.help.step4"] = "Open <code>https://api.telegram.org/bot&lt;TOKEN&gt;/getUpdates</code> in a browser, find <code>\"chat\":{\"id\":...}</code> and copy that number into <em>Chat ID</em>.",
                ["settings.telegram.help.step5"] = "Save again, then click <em>Send test message</em> below to confirm everything works.",
                ["settings.telegram.help.note"] = "For group chats the chat_id is negative (starts with -100…). Add the bot to the group first, then run getUpdates.",
                ["settings.scan_interval"] = "Subnet scan interval (s)",
                ["settings.zscore"] = "Anomaly z-score threshold",
                ["settings.save"] = "Save",
                ["settings.saved"] = "Saved.",
                ["settings.admin_only"] = "Only admin users can change settings.",
                ["profile.title"] = "User Profile",
                ["profile.theme"] = "Interface Theme",
                ["profile.theme.subtitle"] = "Switch between dark and light",
                ["profile.theme.toLight"] = "☀ Switch to Light",
                ["profile.theme.toDark"] = "🌙 Switch to Dark",
                ["profile.lang"] = "Language",
                ["profile.lang.subtitle"] = "Interface language",
                ["profile.password"] = "Change password",
                ["profile.password.current"] = "Current password",
                ["profile.password.new"] = "New password",
                ["profile.password.submit"] = "Change",
                ["profile.password.ok"] = "Password changed.",
                ["profile.password.bad"] = "Current password is incorrect.",
                ["nav.anomalies"] = "Anomalies",
                ["nav.devices"] = "Devices",
                ["nav.admin"] = "Admin",
                ["topbar.critical"] = "critical",
                ["topbar.no_agent"] = "no agent",
                ["topbar.no_agent.tip"] = "No agent has reported in the last 60 seconds. Start NetVigil.Agent on a host inside the watched network.",
                ["topbar.agents"] = "agents",
                ["devices.page.title"] = "All Devices",
                ["devices.page.subtitle"] = "Click any column header to sort. Flag a device to mark it for review.",
                ["devices.col.mac"] = "MAC",
                ["devices.col.anom24h"] = "Anom/24h",
                ["anomalies.page.title"] = "Anomaly Log",
                ["anomalies.page.subtitle"] = "All detected anomalies; flag a device to mark it for review.",
                ["anomalies.flag"] = "Flag device",
                ["anomalies.unflag"] = "Unflag",
                ["anomalies.flagged"] = "Flagged",
                ["anomalies.col.score"] = "Score",
                ["anomalies.col.summary"] = "Summary",
                ["anomalies.filter.only_flagged"] = "Only flagged",
                ["anomalies.summary.warmup"] = "Warming up",
                ["anomalies.summary.ok"] = "Normal",
                ["anomalies.summary.if"] = "IF score {0:F2}",
                ["anomalies.summary.zscore"] = "z={0:F2} (μ={1:F1} Mbps, σ={2:F1})",
                ["severity.normal"] = "Normal",
                ["severity.suspicious"] = "Suspicious",
                ["severity.anomalous"] = "Anomalous",
                ["severity.critical"] = "Critical",
                ["common.loading"] = "Loading…",
                ["common.no_users"] = "No users.",
                ["common.error"] = "Something went wrong",
                ["common.error_help"] = "An unexpected error occurred while rendering this page.",
                ["common.retry"] = "Retry",
                ["chart.anomaly_badge"] = "ANOMALY",
                ["devices.flagged"] = "Flagged",
                ["settings.detection"] = "Detection",
                ["login.page"] = "Login",
                ["admin.title"] = "User Management",
                ["admin.subtitle"] = "Create and manage operator accounts.",
                ["admin.col.id"] = "ID",
                ["admin.col.username"] = "Username",
                ["admin.col.role"] = "Role",
                ["admin.col.created"] = "Created",
                ["admin.col.last"] = "Last login",
                ["admin.col.actions"] = "Actions",
                ["admin.role.admin"] = "Admin",
                ["admin.role.viewer"] = "Viewer",
                ["admin.create"] = "Create user",
                ["admin.delete"] = "Delete",
                ["admin.reset"] = "Reset password",
                ["admin.promote"] = "Promote to Admin",
                ["admin.demote"] = "Demote to Viewer",
                ["admin.new.username"] = "New username",
                ["admin.new.password"] = "Initial password (≥6 chars)",
                ["admin.new.role"] = "Role",
                ["admin.new.create"] = "Create",
                ["admin.never"] = "never",
                ["admin.confirm.delete"] = "Delete user '{0}'?",
                ["admin.confirm.reset"] = "Reset password for '{0}'? Server will generate a new one.",
                ["admin.new.password_hint"] = "Server generates the initial password and shows it once. The user must change it on first sign-in.",
                ["admin.gen.title"] = "New password",
                ["admin.gen.desc"] = "Share this password with '{0}'. They will be required to change it on first sign-in.",
                ["admin.gen.copy"] = "Copy",
                ["admin.gen.copied"] = "Copied to clipboard",
                ["admin.gen.warn"] = "This password will not be shown again. Save it now.",
                ["admin.gen.done"] = "Done",
                ["first_login.title"] = "Set a new password",
                ["first_login.subtitle"] = "Your account was issued a temporary password. Choose a new one to continue.",
                ["first_login.current"] = "Temporary password",
                ["first_login.new"] = "New password",
                ["first_login.confirm"] = "Confirm new password",
                ["first_login.submit"] = "Save and sign out",
                ["first_login.err.empty"] = "Fill in both passwords.",
                ["first_login.err.mismatch"] = "Passwords do not match.",
                ["first_login.err.same"] = "New password must differ from the temporary one.",
                ["first_login.err.weak"] = "Password must be at least 8 characters with letters and digits.",
                ["first_login.err.rejected"] = "Server rejected the password change.",
                ["theme.toggle"] = "Toggle theme",
                ["nav.insights"] = "ML insights",
                ["chart.full"] = "Fullscreen",
                ["chart.exit_full"] = "Exit fullscreen",
                ["anomalies.cta.more"] = "View {0} more →",
                ["anomalies.cta.open"] = "Open anomaly log",
                ["insights.title"] = "Detector insights",
                ["insights.subtitle"] = "How the anomaly model is learning and what it sees right now.",
                ["insights.updated"] = "Updated",
                ["insights.kind"] = "Detector",
                ["insights.status.ready"] = "Trained · scoring",
                ["insights.status.warmup"] = "Warming up · collecting samples",
                ["insights.samples"] = "Samples observed",
                ["insights.samples.sub"] = "since process start",
                ["insights.lastTrain"] = "Last training",
                ["insights.lastTrain.never"] = "not yet",
                ["insights.lastTrain.every"] = "every",
                ["insights.criticalNow"] = "Critical right now",
                ["insights.criticalNow.sub"] = "devices above critical threshold",
                ["insights.reservoir"] = "Reservoir buffer",
                ["insights.reservoir.help"] = "Algorithm R reservoir — every observed sample has an equal chance of being kept and used in the next retraining cycle.",
                ["insights.window"] = "Per-device windows",
                ["insights.window.unit"] = "samples",
                ["insights.window.help"] = "Z-score keeps a per-device rolling window. A device starts producing scores after 10 samples.",
                ["insights.population"] = "Current population by risk",
                ["insights.population.unit"] = "devices",
                ["insights.params"] = "Model parameters",
                ["insights.params.trees"] = "Trees",
                ["insights.params.subsample"] = "Subsample size",
                ["insights.params.depth"] = "Max depth",
                ["insights.params.mbpsRange"] = "Mbps train range",
                ["insights.params.algo"] = "Algorithm",
                ["insights.params.warmup"] = "Warm-up requirement",
                ["insights.thresholds"] = "Severity thresholds",
                ["insights.thresholds.if"] = "Score is in [0, 1]; higher = shorter isolation path = more anomalous.",
                ["insights.thresholds.zscore"] = "Standard deviations from the per-device rolling mean.",
                ["insights.ago"] = "ago"
            },
            ["ru"] = new()
            {
                ["nav.dashboard"] = "Дашборд",
                ["nav.settings"] = "Настройки",
                ["nav.profile"] = "Профиль",
                ["nav.logout"] = "Выйти",
                ["dashboard.title"] = "Сетевая панель",
                ["dashboard.subtitle"] = "Мониторинг в реальном времени",
                ["dashboard.refresh"] = "Обновить",
                ["dashboard.scanning"] = "Сканирую...",
                ["dashboard.connecting"] = "Подключение к серверу...",
                ["stats.online_devices"] = "Онлайн устройств",
                ["stats.total_traffic"] = "Общий трафик",
                ["stats.anomalies_24h"] = "Аномалий (24ч)",
                ["stats.critical_devices"] = "Критичных устройств",
                ["stats.devices"]  = "Онлайн устройств",
                ["stats.traffic"]  = "Общий трафик",
                ["stats.anomalies"]= "Аномалий (24ч)",
                ["stats.critical"] = "Критичных",
                ["chart.title"]    = "Сетевой трафик",
                ["chart.range"]    = "В реальном времени · 5 мин",
                ["chart.waiting"]  = "Ожидаю данные от агента…",
                ["devices.title"]  = "Подключённые устройства",
                ["devices.empty"]  = "Устройства не обнаружены. Проверь что агент запущен.",
                ["devices.col.status"] = "Статус",
                ["devices.col.name"]   = "Устройство",
                ["devices.col.ip"]     = "IP-адрес",
                ["devices.col.vendor"] = "Производитель",
                ["devices.col.seen"]   = "Последний раз",
                ["devices.online"]  = "Онлайн",
                ["devices.offline"] = "Офлайн",
                ["anomalies.title"] = "Последние аномалии",
                ["anomalies.empty"] = "Аномалии не обнаружены.",
                ["anomalies.col.time"]     = "Время",
                ["anomalies.col.device"]   = "Устройство",
                ["anomalies.col.severity"] = "Уровень",
                ["login.title"] = "Вход в NetVigil",
                ["login.username"] = "Логин",
                ["login.password"] = "Пароль",
                ["login.submit"] = "Войти",
                ["login.error"] = "Неверный логин или пароль.",
                ["settings.title"] = "Настройки системы",
                ["settings.telegram"] = "Уведомления Telegram",
                ["settings.telegram.enabled"] = "Включить уведомления",
                ["settings.telegram.token"] = "Токен бота",
                ["settings.telegram.chat"] = "ID чата",
                ["settings.telegram.test"] = "Отправить тестовое сообщение",
                ["settings.telegram.test.ok"] = "Отправлено — проверь Telegram.",
                ["settings.telegram.test.fail"] = "Не отправлено — см. ошибку.",
                ["settings.telegram.help.toggle"] = "Как настроить",
                ["settings.telegram.help.title"] = "У NetVigil нет общего бота — каждый админ заводит свой.",
                ["settings.telegram.help.step1"] = "Открой <code>@BotFather</code> в Telegram, отправь <code>/newbot</code>, придумай имя и скопируй токен (вида <code>123456789:ABC...</code>).",
                ["settings.telegram.help.step2"] = "Вставь токен в поле <em>Токен бота</em> и нажми Сохранить.",
                ["settings.telegram.help.step3"] = "В Telegram напиши своему боту любое сообщение — пока ты ему не написал, он не сможет писать тебе.",
                ["settings.telegram.help.step4"] = "Открой <code>https://api.telegram.org/bot&lt;TOKEN&gt;/getUpdates</code> в браузере, найди <code>\"chat\":{\"id\":...}</code> и впиши этот номер в поле <em>ID чата</em>.",
                ["settings.telegram.help.step5"] = "Сохрани ещё раз, затем нажми <em>Отправить тестовое сообщение</em> — проверишь, что всё работает.",
                ["settings.telegram.help.note"] = "Для групповых чатов chat_id отрицательный (начинается с -100…). Сначала добавь бота в группу, затем запроси getUpdates.",
                ["settings.scan_interval"] = "Интервал сканирования сети (с)",
                ["settings.zscore"] = "Порог аномалии (z-score)",
                ["settings.save"] = "Сохранить",
                ["settings.saved"] = "Сохранено.",
                ["settings.admin_only"] = "Менять настройки может только администратор.",
                ["profile.title"] = "Профиль",
                ["profile.theme"] = "Тема интерфейса",
                ["profile.theme.subtitle"] = "Тёмная или светлая",
                ["profile.theme.toLight"] = "☀ Светлая",
                ["profile.theme.toDark"] = "🌙 Тёмная",
                ["profile.lang"] = "Язык",
                ["profile.lang.subtitle"] = "Язык интерфейса",
                ["profile.password"] = "Сменить пароль",
                ["profile.password.current"] = "Текущий пароль",
                ["profile.password.new"] = "Новый пароль",
                ["profile.password.submit"] = "Сменить",
                ["profile.password.ok"] = "Пароль обновлён.",
                ["profile.password.bad"] = "Неверный текущий пароль.",
                ["nav.anomalies"] = "Аномалии",
                ["nav.devices"] = "Устройства",
                ["nav.admin"] = "Админ",
                ["topbar.critical"] = "критичных",
                ["topbar.no_agent"] = "нет агента",
                ["topbar.no_agent.tip"] = "Ни один агент не отчитался за последние 60 секунд. Запусти NetVigil.Agent на хосте внутри отслеживаемой сети.",
                ["topbar.agents"] = "агентов",
                ["devices.page.title"] = "Все устройства",
                ["devices.page.subtitle"] = "Клик по заголовку — сортировка. Поставь флаг чтобы пометить устройство для разбора.",
                ["devices.col.mac"] = "MAC",
                ["devices.col.anom24h"] = "Аном/24ч",
                ["anomalies.page.title"] = "Журнал аномалий",
                ["anomalies.page.subtitle"] = "Все зафиксированные аномалии; отметь устройство флагом, чтобы пометить его для разбора.",
                ["anomalies.flag"] = "Флаг",
                ["anomalies.unflag"] = "Снять",
                ["anomalies.flagged"] = "Помечено",
                ["anomalies.col.score"] = "Скоринг",
                ["anomalies.col.summary"] = "Сводка",
                ["anomalies.filter.only_flagged"] = "Только флаг",
                ["anomalies.summary.warmup"] = "Прогрев",
                ["anomalies.summary.ok"] = "Норма",
                ["anomalies.summary.if"] = "IF score {0:F2}",
                ["anomalies.summary.zscore"] = "z={0:F2} (μ={1:F1} Мбит/с, σ={2:F1})",
                ["severity.normal"] = "Норма",
                ["severity.suspicious"] = "Подозрительно",
                ["severity.anomalous"] = "Аномалия",
                ["severity.critical"] = "Критично",
                ["common.loading"] = "Загрузка…",
                ["common.no_users"] = "Нет пользователей.",
                ["common.error"] = "Что-то пошло не так",
                ["common.error_help"] = "При отрисовке страницы возникла непредвиденная ошибка.",
                ["common.retry"] = "Повторить",
                ["chart.anomaly_badge"] = "АНОМАЛИЯ",
                ["devices.flagged"] = "Флаг",
                ["settings.detection"] = "Детектор",
                ["login.page"] = "Вход",
                ["admin.title"] = "Управление пользователями",
                ["admin.subtitle"] = "Создание и редактирование учёток операторов.",
                ["admin.col.id"] = "ID",
                ["admin.col.username"] = "Логин",
                ["admin.col.role"] = "Роль",
                ["admin.col.created"] = "Создан",
                ["admin.col.last"] = "Последний вход",
                ["admin.col.actions"] = "Действия",
                ["admin.role.admin"] = "Администратор",
                ["admin.role.viewer"] = "Оператор",
                ["admin.create"] = "Создать пользователя",
                ["admin.delete"] = "Удалить",
                ["admin.reset"] = "Сбросить пароль",
                ["admin.promote"] = "Сделать админом",
                ["admin.demote"] = "Понизить до оператора",
                ["admin.new.username"] = "Новый логин",
                ["admin.new.password"] = "Начальный пароль (≥6 симв.)",
                ["admin.new.role"] = "Роль",
                ["admin.new.create"] = "Создать",
                ["admin.never"] = "никогда",
                ["admin.confirm.delete"] = "Удалить пользователя '{0}'?",
                ["admin.confirm.reset"] = "Сбросить пароль для '{0}'? Сервер сгенерирует новый.",
                ["admin.new.password_hint"] = "Сервер сам сгенерирует пароль и покажет его один раз. Пользователь обязан сменить его при первом входе.",
                ["admin.gen.title"] = "Новый пароль",
                ["admin.gen.desc"] = "Передай этот пароль '{0}'. При первом входе ему придётся сменить его.",
                ["admin.gen.copy"] = "Копировать",
                ["admin.gen.copied"] = "Скопировано в буфер обмена",
                ["admin.gen.warn"] = "Этот пароль больше не будет показан. Сохрани его сейчас.",
                ["admin.gen.done"] = "Готово",
                ["first_login.title"] = "Установите новый пароль",
                ["first_login.subtitle"] = "Учётной записи назначен временный пароль. Чтобы продолжить, придумайте свой.",
                ["first_login.current"] = "Временный пароль",
                ["first_login.new"] = "Новый пароль",
                ["first_login.confirm"] = "Повторите новый пароль",
                ["first_login.submit"] = "Сохранить и выйти",
                ["first_login.err.empty"] = "Заполните оба поля пароля.",
                ["first_login.err.mismatch"] = "Пароли не совпадают.",
                ["first_login.err.same"] = "Новый пароль должен отличаться от временного.",
                ["first_login.err.weak"] = "Минимум 8 символов с буквами и цифрами.",
                ["first_login.err.rejected"] = "Сервер отклонил смену пароля.",
                ["theme.toggle"] = "Сменить тему",
                ["nav.insights"] = "ML-метрики",
                ["chart.full"] = "На всю страницу",
                ["chart.exit_full"] = "Свернуть",
                ["anomalies.cta.more"] = "Показать ещё {0} →",
                ["anomalies.cta.open"] = "Открыть журнал аномалий",
                ["insights.title"] = "Метрики детектора",
                ["insights.subtitle"] = "Как обучается модель и что она видит прямо сейчас.",
                ["insights.updated"] = "Обновлено",
                ["insights.kind"] = "Детектор",
                ["insights.status.ready"] = "Обучен · скорит",
                ["insights.status.warmup"] = "Прогрев · копит сэмплы",
                ["insights.samples"] = "Сэмплов получено",
                ["insights.samples.sub"] = "с момента запуска процесса",
                ["insights.lastTrain"] = "Последнее обучение",
                ["insights.lastTrain.never"] = "ещё не было",
                ["insights.lastTrain.every"] = "каждые",
                ["insights.criticalNow"] = "Критичных сейчас",
                ["insights.criticalNow.sub"] = "устройств выше критического порога",
                ["insights.reservoir"] = "Резервуар сэмплов",
                ["insights.reservoir.help"] = "Алгоритм R: каждый наблюдаемый сэмпл имеет равный шанс попасть в обучающую выборку для следующего ретрейна.",
                ["insights.window"] = "Окна по устройствам",
                ["insights.window.unit"] = "сэмплов",
                ["insights.window.help"] = "Z-score копит rolling-окно для каждого устройства. Скор появляется начиная с 10-го сэмпла.",
                ["insights.population"] = "Текущая популяция по уровню риска",
                ["insights.population.unit"] = "устройств",
                ["insights.params"] = "Параметры модели",
                ["insights.params.trees"] = "Деревьев",
                ["insights.params.subsample"] = "Размер подвыборки",
                ["insights.params.depth"] = "Макс. глубина",
                ["insights.params.mbpsRange"] = "Диапазон Mbps в обучении",
                ["insights.params.algo"] = "Алгоритм",
                ["insights.params.warmup"] = "Требуется для прогрева",
                ["insights.thresholds"] = "Пороги серьёзности",
                ["insights.thresholds.if"] = "Скор в [0, 1]; выше = короче путь изоляции = аномальнее.",
                ["insights.thresholds.zscore"] = "Стандартные отклонения от скользящего среднего по устройству.",
                ["insights.ago"] = "назад"
            }
        };
    }
}
