apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: netvigil-timescale
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: netvigil
    user: postgres
    secureJsonData:
      password: password123
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
    isDefault: true
    editable: true
